version: "3.7"

services: 
    web_app: 
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "python manage.py migrate && python mange.py runserver 0.0.0.0:8000
        ports: 
            - 8000:8000
        restart: "on-failure"
        volumes:
            - .:/home/appuser/test_monitor
        env_file:
            - .env
        depends_on: 
            - db
            - redis


    db: 
        image: postgres:11-alpine
        volumes:
            - .data/db:/var/lib/postgresql
        env_file:
            - .env
        expose:
            - 5432
        environment:
            - 'POSTGRES_HOST=ec2-34-227-120-79.compute-1.amazonaws.com'
            - 'POSTGRES_DB=dqem1lrgkcgls'
            - 'POSTGRES_PORT=5432'
            - 'POSTGRES_USER=zfdxlpxgrkmsyj'
            - 'POSTGRES_PASSWORD=fea8e6a0db9914ea0e622d6da1873265dab186f78d3963795fac26054e68d721'
        restart: "on-failure"


    redis:
        image: redis:alpine


    celery:
        build:
            context: .
        command: celery -A test_monitor worker -l info
        restart: "always"
        volumes:
            - .:/home/appuser/test_monitor
        depends_on:
            - web_app
            - db
            - redis

