# Generated by Django 3.0.7 on 2022-09-09 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='SubQuestions',
        ),
        migrations.AlterField(
            model_name='subquestions',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Question'),
        ),
    ]
