# Generated by Django 3.0.7 on 2022-09-09 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20220909_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subquestions',
            old_name='user_fk',
            new_name='question_fk',
        ),
        migrations.AddField(
            model_name='question',
            name='user_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
