# Generated by Django 3.0.7 on 2022-09-11 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20220909_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='user_fk',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_fk',
        ),
        migrations.RemoveField(
            model_name='useridentity',
            name='acount_type',
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='semester',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='student_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monitor.Students'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='teacher_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monitor.Teachers'),
            preserve_default=False,
        ),
    ]
