# Generated by Django 3.0.7 on 2022-09-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20220911_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='name',
        ),
        migrations.AddField(
            model_name='students',
            name='level',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='user_role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
