# Generated by Django 3.0.7 on 2022-09-12 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20220912_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='question',
            name='year',
        ),
        migrations.AddField(
            model_name='courses',
            name='semester',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monitor.Courses'),
            preserve_default=False,
        ),
    ]
