# Generated by Django 3.0.7 on 2022-09-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20220912_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='caourse_name',
            new_name='course_name',
        ),
    ]
