# Generated by Django 3.0.7 on 2022-09-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20220912_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scheduled', models.DateTimeField(blank=True, null=True)),
                ('show_now', models.CharField(choices=[('open', 'open'), ('close', 'close')], default='close', max_length=10)),
                ('question_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.Question')),
            ],
        ),
    ]
