# Generated by Django 3.0.7 on 2022-09-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_scheduletest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subquestions',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='scheduletest',
            name='question_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='monitor.Question'),
        ),
    ]
