# Generated by Django 3.0.7 on 2022-09-17 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_auto_20220916_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('question_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Question')),
                ('student_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Students')),
            ],
        ),
    ]
