# Generated by Django 3.0.7 on 2022-09-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_auto_20220919_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
