# Generated by Django 3.0.7 on 2022-09-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_question_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=20, null=True),
        ),
    ]
